name: Update Download Count

on:
  schedule:
    - cron: '0 0/3 * * 0'  # Run every 3 hours
  workflow_dispatch:  # Manual trigger

jobs:
  update-count:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.2'

      - name: load library
        run: |
          library(cranlogs)

      - name: Run R script to fetch download count
        run: |
          Rscript get_downloads.R

      - name: Commit and push the updated count
        uses: EndBug/add-and-commit@v7
        with:
          author_name: 'GitHub Actions'
          author_email: 'github-actions@github.com'
          message: 'Update download count'
