name: Update MPCR1 Downloads

on:
  schedule:
    - cron: '0 */2 * * *'  # Runs every 2 hours
  workflow_dispatch:  # Allows manual runs if needed

jobs:
  update-downloads:
    runs-on: ubunutu-latest  # Use a valid runner (e.g., ubuntu-latest)
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated checkout action

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        run: |
          Rscript -e 'install.packages("cranlogs")'

      - name: Fetch download count
        run: |
          Rscript -e 'downloads <- cranlogs::cran_downloads("MPCR1", from = Sys.Date() - 30, to = Sys.Date()); count <- sum(downloads$count); write(count, "downloads.txt")'

      - name: Update README with download count
        run: |
          count=$(cat downloads.txt)
          sed -i "/^<!--downloads-->/,/^<!--downloads-end-->/c\<!--downloads-->\n**Total downloads this month**: $count\n<!--downloads-end-->" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add README.md
          git commit -m "Update MPCR1 download count"
          git push
